version: 1.0.0-{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

init:
  - git config --global core.autocrlf true

before_build:
  - dotnet --version
  - dotnet restore --verbosity m

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

test:
  assemblies:
    only:
      - 'UnitTests\bin\**\UnitTests.dll'

# artifacts:
#   - path: '**\*.nupkg'
